In [3]:
import pandas as pd

In [4]:
reasons = pd.read_csv("./../DashboardCreation/nationalreasonsdata.csv")
reasons.head()

,electionyear,nonvotersinthousands,illnessordisability,outoftownawayfromhome,forgot,notinterested,toobusy,transportationproblems,didnotlikecandidatesorcampaignissues,registrationproblems,badweatherconditions,inconvenientpollingplaceorhourorlinestoolong,otherreason,refused
0,2000,18724,0.148,0.102,0.040,0.122,0.209,0.024,0.077,0.069,0.006,0.026,0.102,0.075
1,2004,16334,0.154,0.090,0.034,0.107,0.199,0.021,0.099,0.068,0.005,0.030,0.109,0.085
2,2016,18933,0.117,0.079,0.030,0.154,0.143,0.026,0.248,0.044,0.000,0.021,0.111,0.027
3,2012,19141,0.140,0.086,0.039,0.157,0.189,0.033,0.127,0.055,0.008,0.027,0.111,0.030
4,2008,15167,0.149,0.088,0.026,0.134,0.175,0.026,0.129,0.060,0.002,0.027,0.113,0.070

In [6]:
competitive = pd.read_csv("./../DashboardCreation/compeditivenessdata.csv")
competitive.head()

,yearstate,electionyear,stateabbreviation,democratcandidatevotes,republicancandidatevotes,othercandidatevotes,totalvotes,percentdemocrat,percentrepublican,percentother,firstplace,secondplace,competivness
0,2000-AK,2000,AK,124376,358260,77317,559953,0.22,0.6398,0.1381,0.6398,0.2200,0.4198
1,2000-AL,2000,AL,1178271,1790402,136593,3105266,0.38,0.5766,0.0440,0.5766,0.3800,0.1966
2,2000-AR,2000,AR,778134,750086,26326,1554546,0.50,0.4825,0.0169,0.5000,0.4825,0.0175
3,2000-AZ,2000,AZ,1243190,2744563,406995,4394748,0.28,0.6245,0.0926,0.6245,0.2800,0.3445
4,2000-CA,2000,CA,17200888,12900577,1925670,32027135,0.54,0.4028,0.0601,0.5400,0.4028,0.1372